require "prototypes.recipe.vanilla"
require "prototypes.recipe.tier4"
require "prototypes.recipe.tier5"
require "prototypes.recipe.tier6"
require "prototypes.recipe.tier7"
require "prototypes.recipe.tier8"
require "prototypes.recipe.tier9"
require "prototypes.recipe.tier10"