local multiplier = settings.startup["deadlock-stack-size"].value
data:extend {
  {
    type = "recipe",
    name = "micro-deadlock-stack-steel-plate",
    category = "micro-furnace-smelting",
    enabled = false,
    energy_required = 3.2,
    ingredients = { { name = "deadlock-stack-iron-ore", amount = 50, type = "item" } },
    results = { { name = "deadlock-stack-steel-plate", amount = 10, type = "item" } },
  },
  {
    type = "recipe",
    name = "micro-deadlock-stack-iron-plate",
    category = "micro-furnace-smelting",
    enabled = false,
    energy_required = 3.2,
    ingredients = { { name = "deadlock-stack-iron-ore", amount = 10, type = "item" } },
    results = { { name = "deadlock-stack-iron-plate", amount = 10, type = "item" } },
  },
  {
    type = "recipe",
    name = "micro-deadlock-stack-copper-plate",
    category = "micro-furnace-smelting",
    enabled = false,
    energy_required = 3.2,
    ingredients = { { name = "deadlock-stack-copper-ore", amount = 10, type = "item" } },
    results = { { name = "deadlock-stack-copper-plate", amount = 10, type = "item" } },
  },
  {
    type = "recipe",
    name = "micro-deadlock-stack-stone-plate",
    category = "micro-furnace-smelting",
    enabled = false,
    energy_required = 3.2,
    ingredients = { { name = "deadlock-stack-stone", amount = 10, type = "item" } },
    results = { { name = "deadlock-stack-stone-brick", amount = 10, type = "item" } },
  },
  {
    type = "recipe",
    name = "micro-deadlock-stack-steel-plate-direct",
    category = "micro-furnace-smelting",
    enabled = false,
    energy_required = 3.2,
    ingredients = { { name = "deadlock-stack-iron-ore", amount = 50, type = "item" } },
    results = { { name = "steel-plate", amount = (10 * multiplier), type = "item" } },
  },
  {
    type = "recipe",
    name = "micro-deadlock-stack-iron-plate-direct",
    category = "micro-furnace-smelting",
    enabled = false,
    energy_required = 3.2,
    ingredients = { { name = "deadlock-stack-iron-ore", amount = 10, type = "item" } },
    results = { { name = "iron-plate", amount = (10 * multiplier), type = "item" } },
  },
  {
    type = "recipe",
    name = "micro-deadlock-stack-copper-plate-direct",
    category = "micro-furnace-smelting",
    enabled = false,
    energy_required = 3.2,
    ingredients = { { name = "deadlock-stack-copper-ore", amount = 10, type = "item" } },
    results = { { name = "copper-plate", amount = (10 * multiplier), type = "item" } },
  },
  {
    type = "recipe",
    name = "micro-deadlock-stack-stone-plate-direct",
    category = "micro-furnace-smelting",
    enabled = false,
    energy_required = 3.2,
    ingredients = { { name = "deadlock-stack-stone", amount = 10, type = "item" } },
    results = { { name = "stone-brick", amount = (10 * multiplier), type = "item" } },
  },
}
if mods["Krastorio2"] then
  data:extend(
    {
      {
        type = "recipe",
        name = "micro-deadlock-stack-glass",
        category = "micro-furnace-smelting",
        enabled = false,
        energy_required = 3.2,
        ingredients = { { name = "deadlock-stack-sand", amount = 20, type = "item" } },
        results = { { name = "deadlock-stack-glass", amount = 10, type = "item" } },
      },
      {
        type = "recipe",
        name = "micro-deadlock-stack-coke",
        category = "micro-furnace-smelting",
        enabled = false,
        energy_required = 3.2,
        ingredients = {
          { name = "deadlock-stack-coal", amount = 12, type = "item" },
          { name = "deadlock-stack-wood", amount = 12, type = "item" }
        },
        results = { { name = "deadlock-stack-coke", amount = 12, type = "item" } },
      },
      {
        type = "recipe",
        name = "micro-deadlock-stack-silicon",
        category = "micro-furnace-smelting",
        enabled = false,
        energy_required = 3.2,
        ingredients = { { name = "deadlock-stack-quartz", amount = 20, type = "item" } },
        results = { { name = "deadlock-stack-silicon", amount = 10, type = "item" } },
      },
      {
        type = "recipe",
        name = "micro-deadlock-stack-rare-metals",
        category = "micro-furnace-smelting",
        enabled = false,
        energy_required = 3.2,
        ingredients = { { name = "deadlock-stack-raw-rare-metals", amount = 20, type = "item" } },
        results = { { name = "deadlock-stack-rare-metals", amount = 10, type = "item" } },
      },
      {
        type = "recipe",
        name = "micro-deadlock-stack-glass-direct",
        category = "micro-furnace-smelting",
        enabled = false,
        energy_required = 3.2,
        ingredients = { { name = "deadlock-stack-sand", amount = 20, type = "item" } },
        results = { { name = "glass", amount = (10 * multiplier), type = "item" } },
      },
      {
        type = "recipe",
        name = "micro-deadlock-stack-coke-direct",
        category = "micro-furnace-smelting",
        enabled = false,
        energy_required = 3.2,
        ingredients = {
          { name = "deadlock-stack-coal", amount = 12, type = "item" },
          { name = "deadlock-stack-wood", amount = 12, type = "item" }
        },
        results = { { name = "coke", amount = (12 * multiplier), type = "item" } },
      },
      {
        type = "recipe",
        name = "micro-deadlock-stack-silicon-direct",
        category = "micro-furnace-smelting",
        enabled = false,
        energy_required = 3.2,
        ingredients = { { name = "deadlock-stack-quartz", amount = 20, type = "item" } },
        results = { { name = "silicon", amount = (10 * multiplier), type = "item" } },
      },
      {
        type = "recipe",
        name = "micro-deadlock-stack-rare-metals-direct",
        category = "micro-furnace-smelting",
        enabled = false,
        energy_required = 3.2,
        ingredients = { { name = "deadlock-stack-raw-rare-metals", amount = 20, type = "item" } },
        results = { { name = "rare-metals", amount = (10 * multiplier), type = "item" } },
      },
    }
  )
end
