data:extend {
  {
    type = "recipe",
    category = "advanced-crafting",
    name = "micro-furnace",
    enabled = false,
    ingredients = {
      { name = "electric-furnace",   amount = 48, type = "item" },
      { name = "bulk-inserter",     amount = 5,  type = "item" },
      { name = "steel-plate",        amount = 50, type = "item" },
      { name = "electronic-circuit", amount = 20, type = "item" },
      { name = "iron-gear-wheel",    amount = 20, type = "item" },
      { name = "iron-stick",         amount = 20, type = "item" },
    },
    energy_required = 30,
    results = { { name = "micro-furnace", amount = 1, type = "item" } },
  },
  {
    type = "recipe",
    category = "advanced-crafting",
    name = "micro-fast-furnace",
    enabled = false,
    ingredients = {
      { name = "micro-furnace",    amount = 2,   type = "item" },
      { name = "bulk-inserter",   amount = 10,  type = "item" },
      { name = "steel-plate",      amount = 100, type = "item" },
      { name = "advanced-circuit", amount = 20,  type = "item" },
      { name = "iron-gear-wheel",  amount = 20,  type = "item" },
      { name = "iron-stick",       amount = 20,  type = "item" },
    },
    energy_required = 30,
    results = { { name = "micro-fast-furnace", amount = 1, type = "item" } },
  },
  {
    type = "recipe",
    category = "crafting-with-fluid",
    name = "micro-express-furnace",
    enabled = false,
    ingredients = {
      { name = "micro-fast-furnace", amount = 2,         type = "item" },
      { name = "bulk-inserter",     amount = 15,        type = "item" },
      { name = "steel-plate",        amount = 200,       type = "item" },
      { name = "advanced-circuit",   amount = 50,        type = "item" },
      { name = "iron-gear-wheel",    amount = 20,        type = "item" },
      { name = "iron-stick",         amount = 20,        type = "item" },
      { type = "fluid",              name = "lubricant", amount = 200 },
    },
    energy_required = 30,
    results = { { name = "micro-express-furnace", amount = 1, type = "item" } },
  },
}
